version: 1
groups:
  - annotation: ckanext-pygments
    options:
      - key: ckanext.pygments.supported_formats
        type: list
        description: Specify a list of supported formats
        default: sql html xhtml htm xslt py pyw pyi jy sage sc rs rs.in rst rest md markdown xml xsl rss xslt xsd wsdl wsf json jsonld yaml yml dtd php inc rdf ttl js

      - key: ckanext.pygments.max_size
        type: int
        description: Specify how many bytes we are going to render from file. Default to 1MB
        default: 1048576

      - key: ckanext.pygments.include_htmx_asset
        description: Include HTMX asset
        default: true
        type: bool

      - key: ckanext.pygments.default_theme
        description: Default theme for preview
        default: default

      - key: ckanext.pygments.cache.enable
        description: Enable cache
        default: false
        type: bool

      - key: ckanext.pygments.cache.resouce_max_size
        description: Specify what is the maximum size of the resource that we are going to cache
        default: 20971520 # 20MB
        type: int
